### ISSUE TITLE
mod rebinds keys

### ISSUE THREAD

**Issue by Eclipse8264** [SFGrenade/NeverMuffle#2]
i like the mod, but it rebinds in-game menu keys (not in minemenu). at in the godhome, use a door the game says to use jump for picking thinks and focus for close, but this mod changes that a you have to use enter for picking thinks and back space for close. can that be fixed?

**Comment by SFGrenade** [comment]
uhm, i don't know which mod does that, but it is definetly not NeverMuffle, as all it does is to not have the muffle effect when being hit.

**Comment by Clazex** [comment]
IMO Unity Explorer should take responsibility of that

**Comment by SFGrenade** [comment]
closing due to irrelevancy and no updates
